version: '2'
services:
  conjur:
    image: cyberark/conjur
    environment:
      CONJUR_ADMIN_PASSWORD: ADmin123!!!!
      DATABASE_URL: postgres://postgres@db
      CONJUR_DATA_KEY: testing//testing//testing//testing//testing=
    volumes:
      - .:/src:ro
    working_dir: /src
    command: server
    depends_on: [db]

  db:
    image: postgres:9.3

  cli:
    environment:
      CONJUR_ACCOUNT: cucumber
      CONJUR_APPLIANCE_URL: http://conjur
    image: conjurinc/cli5
    entrypoint: sleep
    command: infinity
    volumes:
      - .:/src:ro
